### ISSUE TITLE
Remove Comments

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/action-series-discussions#1]
https://github.com/byuitechops/action-series-discussions/blob/36b2dc520d0f17759cb1d3ca63c6e61fe8551ff0/template-discussions.js#L49-L60

Let's remove anything that will break on a PUT request. If it isn't used, then delete it. If we need it again, we can look at old commits.

**Comment by sethchilders92** [comment]
Technically everything included and commented out will work on a PUT request according to the documentation, but I removed everything that isn't common and we can modify it if we need it again.
