### ISSUE TITLE
Discussion HTML

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/action-series-discussions#2]
https://github.com/byuitechops/action-series-discussions/blob/36b2dc520d0f17759cb1d3ca63c6e61fe8551ff0/template-discussions.js#L90-L96

Discussions do have HTML on them. I believe it is called "message" or something. 
https://canvas.instructure.com/doc/api/discussion_topics.html

**Comment by sethchilders92** [comment]
Got it. Nice catch!
